# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1-snapshot-3
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=1.0.5-beta+26.1-snapshots
maven_group=me.imgalvin.playerfinder
archives_base_name=player-finder

# Dependencies
fabric_api_version=0.142.0+26.1
